"""initial migration

Revision ID: 1ed338635dfa
Revises: 
Create Date: 2026-05-11 08:34:05.533112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ed338635dfa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authentications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=300), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('employee_emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('department', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('road_maps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firm', sa.String(length=200), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('industry', sa.String(length=200), nullable=False),
    sa.Column('modules', sa.JSON(), nullable=True),
    sa.Column('reffered_by', sa.String(length=200), nullable=True),
    sa.Column('deal_size', sa.Integer(), nullable=True),
    sa.Column('opportunity_stage', sa.String(length=200), nullable=False),
    sa.Column('exp_closure_date', sa.DateTime(), nullable=True),
    sa.Column('customer_party', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('administrators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('authentication_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['authentication_id'], ['authentications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('authentication_id')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('road_map_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['road_map_id'], ['road_maps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roadmap_assignments',
    sa.Column('roadmap_id', sa.Integer(), nullable=False),
    sa.Column('authentication_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['authentication_id'], ['authentications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['roadmap_id'], ['road_maps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('roadmap_id', 'authentication_id')
    )
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('administrator_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['administrator_id'], ['administrators.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('authentication_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['authentication_id'], ['authentications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('authentication_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employees')
    op.drop_table('departments')
    op.drop_table('roadmap_assignments')
    op.drop_table('comments')
    op.drop_table('administrators')
    op.drop_table('road_maps')
    op.drop_table('employee_emails')
    op.drop_table('authentications')
    # ### end Alembic commands ###
